tools:
  pkg.installed:
    - pkgs:
      - atool
      - bash-completion
      - curl
      - dnsutils
      - gpm
      - htop
      - inotify-tools
      - iotop
      - jnettop
      - lftp
      - lsof
      - nmap
      - python-optcomplete
      - python-pip
      - rsync
      - tmux
      - tree
      - vim-nox
      - wajig
      - whois
